############################
#   DYNAMIXEL ERROR TYPE   #
############################

DXL_COMM_ERROR          = -100
DXL_PACKET_ERROR        = -101
DXL_INVALID_SIZE        = -102
DXL_DATA_UNAVAILABLE    = -103
DXL_OK                  = 0

###########################################
#   DYNAMIXEL XL320 (2.0) CONTROL TABLE   #
###########################################

DXL_XL320_MODEL_NUMBER_ADDR         = 0
DXL_XL320_MODEL_NUMBER_SIZE         = 2

DXL_XL320_ID_ADDR                   = 3
DXL_XL320_ID_SIZE                   = 1

DXL_XL320_BAUDRATE_ADDR             = 4
DXL_XL320_BAUDRATE_SIZE             = 1

DXL_XL320_CONTROL_MODE_ADDR         = 11
DXL_XL320_CONTROL_MODE_SIZE         = 1

DXL_XL320_TORQUE_ENABLE_ADDR        = 24
DXL_XL320_TORQUE_ENABLE_SIZE        = 1

DXL_XL320_LED_ADDR                  = 25
DXL_XL320_LED_SIZE                  = 1

DXL_XL320_GOAL_POSITION_ADDR        = 30
DXL_XL320_GOAL_POSITION_SIZE        = 2

DXL_XL320_GOAL_SPEED_ADDR           = 32
DXL_XL320_GOAL_SPEED_SIZE           = 2

DXL_XL320_PRESENT_POSITION_ADDR     = 37
DXL_XL320_PRESENT_POSITION_SIZE     = 2

DXL_XL320_PRESENT_SPEED_ADDR        = 39
DXL_XL320_PRESENT_SPEED_SIZE        = 2

DXL_XL320_PRESENT_LOAD_ADDR         = 41
DXL_XL320_PRESENT_LOAD_SIZE         = 2

DXL_XL320_PRESENT_VOLTAGE_ADDR      = 45
DXL_XL320_PRESENT_VOLTAGE_SIZE      = 1

DXL_XL320_PRESENT_TEMPERATURE_ADDR  = 46
DXL_XL320_PRESENT_TEMPERATURE_SIZE  = 1

###########################################
#   DYNAMIXEL AX12A (1.0) CONTROL TABLE   #
###########################################

DXL_AX12A_MODEL_NUMBER_ADDR         = 0
DXL_AX12A_MODEL_NUMBER_SIZE         = 2

DXL_AX12A_ID_ADDR                   = 3
DXL_AX12A_ID_SIZE                   = 1

DXL_AX12A_BAUDRATE_ADDR             = 4
DXL_AX12A_BAUDRATE_SIZE             = 1

DXL_AX12A_CW_ANGLE_LIMIT_ADDR       = 6
DXL_AX12A_CW_ANGLE_LIMIT_SIZE       = 2

DXL_AX12A_CCW_ANGLE_LIMIT_ADDR      = 8
DXL_AX12A_CCW_ANGLE_LIMIT_SIZE      = 2

DXL_AX12A_TORQUE_ENABLE_ADDR        = 24
DXL_AX12A_TORQUE_ENABLE_SIZE        = 1

DXL_AX12A_LED_ADDR                  = 25
DXL_AX12A_LED_SIZE                  = 1

DXL_AX12A_GOAL_POSITION_ADDR        = 30
DXL_AX12A_GOAL_POSITION_SIZE        = 2

DXL_AX12A_GOAL_SPEED_ADDR           = 32
DXL_AX12A_GOAL_SPEED_SIZE           = 2

DXL_AX12A_PRESENT_POSITION_ADDR     = 36
DXL_AX12A_PRESENT_POSITION_SIZE     = 2

DXL_AX12A_PRESENT_SPEED_ADDR        = 38
DXL_AX12A_PRESENT_SPEED_SIZE        = 2

DXL_AX12A_PRESENT_LOAD_ADDR         = 40
DXL_AX12A_PRESENT_LOAD_SIZE         = 2

DXL_AX12A_PRESENT_VOLTAGE_ADDR      = 42
DXL_AX12A_PRESENT_VOLTAGE_SIZE      = 1

DXL_AX12A_PRESENT_TEMPERATURE_ADDR  = 43
DXL_AX12A_PRESENT_TEMPERATURE_SIZE  = 1

###########################################
#   DYNAMIXEL MX28 (1.0) CONTROL TABLE   #
###########################################

DXL_MX28_MODEL_NUMBER_ADDR          = 0
DXL_MX28_MODEL_NUMBER_SIZE          = 2

DXL_MX28_ID_ADDR                    = 3
DXL_MX28_ID_SIZE                    = 1

DXL_MX28_BAUDRATE_ADDR              = 4
DXL_MX28_BAUDRATE_SIZE              = 1

DXL_MX28_CW_ANGLE_LIMIT_ADDR        = 6
DXL_MX28_CW_ANGLE_LIMIT_SIZE        = 2

DXL_MX28_CCW_ANGLE_LIMIT_ADDR       = 8
DXL_MX28_CCW_ANGLE_LIMIT_SIZE       = 2

DXL_MX28_TORQUE_ENABLE_ADDR         = 24
DXL_MX28_TORQUE_ENABLE_SIZE         = 1

DXL_MX28_LED_ADDR                   = 25
DXL_MX28_LED_SIZE                   = 1

DXL_MX28_GOAL_POSITION_ADDR         = 30
DXL_MX28_GOAL_POSITION_SIZE         = 2

DXL_MX28_GOAL_SPEED_ADDR            = 32
DXL_MX28_GOAL_SPEED_SIZE            = 2

DXL_MX28_PRESENT_POSITION_ADDR      = 36
DXL_MX28_PRESENT_POSITION_SIZE      = 2

DXL_MX28_PRESENT_SPEED_ADDR         = 38
DXL_MX28_PRESENT_SPEED_SIZE         = 2

DXL_MX28_PRESENT_LOAD_ADDR          = 40
DXL_MX28_PRESENT_LOAD_SIZE          = 2

DXL_MX28_PRESENT_VOLTAGE_ADDR       = 42
DXL_MX28_PRESENT_VOLTAGE_SIZE       = 1

DXL_MX28_PRESENT_TEMPERATURE_ADDR   = 43
DXL_MX28_PRESENT_TEMPERATURE_SIZE   = 1